config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :tasks
  resources :users
  resources :sessions
  namespace :admin do
    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    end
  end
    root to: 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
    before_destroy :admin_user_destroy_action
    before_update :admin_user_update_action
    has_many :tasks, dependent: :destroy
    has_secure_password
    before_save { email.downcase! }
    before_validation { email.downcase! }
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :password, presence: true, length: { minimum: 6 }, on: :create


    private

    def admin_user_destroy_action
      if User.where(admin: true).count == 1 && self.admin
        throw(:abort)
      end
    end   

    def admin_user_update_action
      @admin_user = User.where(admin: true)
      if (@admin_user.count == 1 && @admin_user.first == self) && !(self.admin)      
        throw :abort        

      end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :show, :destroy, :update]
  before_action :require_admin

  def new
    # binding.pry
    @user = User.new
   
  end

  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    # @user = User.find(user_params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:notice] =  "ユーザー #{@user.name} 更新しました"
      redirect_to admin_users_path
    else
      render :edit, notice: "管理者がいなくなります！ #{@user.name} の管理者を外して更新ができません！すまん。"
    end
  end

  def show

  end

  def index
    @users = User.all.includes(:tasks)
    @users = @users.page(params[:page]).per(10)    
  end

  def destroy
    if@user.destroy
      redirect_to admin_users_path, notice: "ユーザー #{@user.name} を削除しました"
    else
      redirect_to admin_users_path, notice: "管理者がいなくなります！ #{@user.name} を削除できません！すまんね。"
    end
  end
 
  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
    
  end

  def require_admin
    unless current_user.admin?
      redirect_to tasks_path, notice: "あなたは管理者ではありません"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:show]
  skip_before_action :login_required
  before_action :set_user, only: [:show, :edit]

  def new
    redirect_to user_path(current_user.id) if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '登録しました'
      redirect_to user_path(@user.id)      
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def show
    # @user = User.find(params[:id])
  end

  def edit
    # @user = User.find(params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |form| %>
  
    <div class="user_list">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="user_list">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="user_list">
      <%= form.label :管理者権限 %>
      <%= form.check_box :admin %>
    </div>

    <div class="user_list">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="user_list">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div> 
    
      <%= form.submit %>
  
<% end %>

app/views/admin/users/edit.html.erb
<h2><%= @user.name %>のページ編集</h2>
<br>
<%= render 'form', user: @user %>

<br>
<br>
<button type="button" class="btn btn-info btn-sm"><%= link_to 'Show', @user %></button>
<button type="button" class="btn btn-info btn-sm"><%= link_to 'Back', user_path %></button>

app/views/admin/users/index.html.erb
<h2>ユーザー登録一覧</h2>

<table class="table">
<br>
  <thead>
    <tr class="table-info">
      <th><%= t('user.id') %></th>
      <th><%= t('user.name') %></th>
      <th><%= t('user.admin') %></th>
      <th><%= t('user.task_count') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.admin %></td>
          <td><%= user.tasks.count %></td> 
          <td><%= link_to 'Show', admin_user_path(user) %></td>
          <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
          <td><%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>  
</table>
<br>
<br>
<button type="button" class="btn btn-success btn-sm"><%= link_to '新規ユーザー作成', new_admin_user_path %></button>
<nav aria-label="Page navigation example"><%= paginate @users %></nav>

app/views/admin/users/new.html.erb
<h1>管理者用 Sign up</h1>
<br>
<br>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<table>
  <thead>
    <tr>
      <th>タスク</th>
      <th>詳細</th>
      <th>期限</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>タグ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td class = "task_list" ><%= task.name %></td>
        <td><%= task.detail %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status_i18n %></td>
        <td><%= task.priority_i18n %></td>
        <td>
          <% task.labels.each do |label| %>
            <%= label.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>